### ISSUE TITLE
Nullpointer exception with multipl font-face source

### ISSUE THREAD

**Issue by kalidasya** [SonarCommunity/sonar-css#117]
The following code is reported to cause nullpointer excepion:
```
@font-face {
  font-family: GDS-Logo;
  src: local("HelveticaNeue"), local("Helvetica Neue"), local("Arial"), local("Helvetica");
}
```
Exception is:
```
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
       at
 org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
       at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
       at java.security.AccessController.doPrivileged(Native Method)
       at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
       at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
       at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
       at org.sonar.runner.api.Runner.execute(Runner.java:100)
       at org.sonar.runner.Main.executeTask(Main.java:70)
       at org.sonar.runner.Main.execute(Main.java:59)
       at org.sonar.runner.Main.main(Main.java:53)
 Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze
 file:
 /var/lib/jenkins/workspace/analysis_sonar_trunk/www/configurations/base/resource/styles/DetailedInfoScreenVod.css
       at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)
       at org.sonar.plugins.css.CssSquidSensor.analyse(CssSquidSensor.java:83)
       at
 org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:59)
       at
 org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:51)
       at
 org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:120)
       at
 org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
       at
 org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
       at
 org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
       at
 org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
       at
 org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
       at
 org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
       at
 org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
       at
 org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
       at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
       at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
       at
 org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
       at
 org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
       at
 org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
       at
 org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
       at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
       at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
       at
 org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
       at
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:606)
       at
 org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
       ... 9 more
 Caused by: java.lang.NullPointerException
       at
 org.sonar.css.checks.DisallowDuplicateBackgroundImages.visitNode(DisallowDuplicateBackgroundImages.java:55)
       at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
       at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
       at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
       at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
       ... 35 more
```

**Comment by kalidasya** [comment]
@racodond will you have time to check this?

**Comment by racodond** [comment]
@kalidasya I'll try to have a look at it this weekend.

**Comment by racodond** [comment]
@kalidasya It's weird that you get a NPE on  org.sonar.css.checks.DisallowDuplicateBackgroundImages.visitNode(DisallowDuplicateBackgroundImages.java:55) with this piece of code. But for sure, there's an issue with the bulletproof-font-face rule with this piece of code. Fix to be reviewed at: https://github.com/SonarCommunity/sonar-css/pull/121
Can you double-check the piece of code and the stack trace? Are you sure you didn't get things mixed up? Could you please provide the whole file?

**Comment by kalidasya** [comment]
@racodond it was reported to on mail, so I did not get the exception. But maybe he meant previously this was NPE and not it is causing other problems. Sorry for the confusion

**Comment by racodond** [comment]
OK
Removing this issue from the 1.4 milestone as the PR is already in the milestone.
Closing the issue.
