### ISSUE TITLE
NullPointerException at org.sonar.css.checks.BulletproofFontFace.visitNode

### ISSUE THREAD

**Issue by dploeger** [SonarCommunity/sonar-css#142]
When running Sonar against a bunch of css-files, it failes with this stacktrace:

```java
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.sonar.runner.Main.executeTask(Main.java:70)
	at org.sonar.runner.Main.execute(Main.java:59)
	at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: /home/teamcity/BuildAgent/work/c5781ec43a72c8ed/build/hybris/bin/custom/project/web/webroot/loc.css
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)
	at org.sonar.plugins.css.CssSquidSensor.analyse(CssSquidSensor.java:91)
	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:59)
	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:51)
	at org.sonar.batch.phases.DatabaseModePhaseExecutor.execute(DatabaseModePhaseExecutor.java:120)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:264)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:235)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:230)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:220)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.sonar.css.checks.BulletproofFontFace.visitNode(BulletproofFontFace.java:67)
	at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
	... 36 more
```

The content of the CSS file it is complaining about is:

```css
@font-face{font-family:'extrabold';src:local('Helvetica'),local('Arial'),local('sans-serif')}@font-face{font-family:'light';src:local('Helvetica'),local('Arial'),local('sans-serif')}@font-face{font-family:'medium';src:local('Helvetica'),local('Arial'),local('sans-serif')}@font-face{font-family:'regular';src:local('Helvetica'),local('Arial'),local('sans-serif')}@font-face{font-family:'thin';src:local('Helvetica'),local('Arial'),local('sans-serif')}.m_nav ul li a{font-weight:bold}.m_nav ul.mdd li a{font-weight:normal}
```

Perhaps this one corresponds to https://github.com/kalidasya/sonar-css/issues/2?

**Comment by racodond** [comment]
@dploeger I just ran an analysis of this piece of code with SonarQube 5.1.2 and version 1.5 of the CSS plugin and it succeeded. Which versions are you running?

Note also that this rule is deprecated in version 1.5. Could you please activate its replacement instead: `"@font-face" rule should be made compatible with the required browsers`?

**Comment by dploeger** [comment]
Sorry. I've updated (I missed the SonarQube update somehow) and it works now. Thanks.

**Comment by racodond** [comment]
Cool!
